name: Publish to Codeberg Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish_html:
    name: "publish html"
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v6

      - uses: https://github.com/actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install sparql-examples-utils
        run: wget "https://github.com/sib-swiss/sparql-examples-utils/releases/download/v2.0.23/sparql-examples-utils-2.0.23-uber.jar" -O sparql-examples-utils-uber.jar

      - name: Generate markdown
        run: java -jar sparql-examples-utils-uber.jar convert -i examples/ -m

      - name: Generate rq files
        run: java -jar sparql-examples-utils-uber.jar convert -i examples/ -r

      - name: Fix generated URLs
        run: find . -name "*.md" ! -path "./_site/*" -exec sed -i 's|/pages/adafede/sparql-examples/|/sparql-examples/|g' {} +

      - name: Write minimal layout and config
        run: |
          mkdir -p _layouts assets/css
          wget "https://pages-themes.github.io/modernist/assets/css/style.css" -O assets/css/style.css
          cat > _layouts/default.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en-US">
            <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>{{ page.title | default: site.title }}</title>
              <link rel="stylesheet" href="{{ '/assets/css/style.css' | prepend: site.baseurl }}">
            </head>
            <body>
              <div class="wrapper">
                <header>
                  <h1><a href="{{ '/' | prepend: site.baseurl }}">{{ site.title }}</a></h1>
                  <p>{{ site.description }}</p>
                  {% if site.github_username %}
                  <p><a href="https://github.com/{{ site.github_username }}/{{ site.github_repo }}">View the Project on GitHub</a></p>
                  {% endif %}
                </header>
                <section>
                  {{ content }}
                </section>
                <footer>
                  <p>Hosted on <a href="https://codeberg.org">Codeberg</a></p>
                </footer>
              </div>
              <script type="module">
                import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';
                document.querySelectorAll('code.language-mermaid').forEach(el => {
                  const div = document.createElement('div');
                  div.className = 'mermaid';
                  div.textContent = el.textContent;
                  el.parentNode.replaceWith(div);
                });
                mermaid.initialize({ startOnLoad: true });
              </script>
            </body>
          </html>
          EOF
          cat > _config.yml << 'EOF'
          baseurl: "/sparql-examples"
          url: "https://adafede.codeberg.page"
          title: "sparql-examples"
          description: "A set of SPARQL examples"
          github_username: Adafede
          github_repo: sparql-examples
          theme: null
          EOF

      - name: Build with Jekyll
        uses: https://github.com/actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Clean up before deploy
        run: rm -f ./_site/sparql-examples-utils-uber.jar

      - name: Deploy to Codeberg Pages
        uses: actions/git-pages@v2
        with:
          site: https://adafede.codeberg.page/sparql-examples/ 
          token: ${{ forge.token }}
          source: ./_site