name: Publish to Codeberg Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish_html:
    name: "publish html"
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v6

      - uses: https://github.com/actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install tester
        run: wget "https://github.com/sib-swiss/sparql-examples-utils/releases/download/v2.0.19/sparql-examples-utils-2.0.19-uber.jar" -O sparql-examples-utils-uber.jar

      - name: Generate markdown
        run: java -jar sparql-examples-utils-uber.jar convert -i examples/ -m

      - name: Generate rq files
        run: java -jar sparql-examples-utils-uber.jar convert -i examples/ -r

      - name: Download modernist theme
        run: |
          mkdir -p _layouts assets/css assets/js
          wget "https://raw.githubusercontent.com/pages-themes/modernist/master/_layouts/default.html" -O _layouts/default.html
          wget "https://raw.githubusercontent.com/pages-themes/modernist/master/assets/css/style.scss" -O assets/css/style.scss
          wget "https://raw.githubusercontent.com/pages-themes/modernist/master/assets/js/scale.fix.js" -O assets/js/scale.fix.js

      - name: Fix theme asset paths in layout
        run: |
          sed -i 's|href="stylesheets/|href="{{ "/assets/stylesheets/" | prepend: site.baseurl }}|g' _layouts/default.html
          sed -i 's|src="javascripts/|src="{{ "/assets/javascripts/" | prepend: site.baseurl }}|g' _layouts/default.html
          sed -i 's|Hosted on Codeberg Pages &mdash; Theme by <a href="https://github.com/orderedlist">orderedlist</a>||g' _layouts/default.html

      - name: Fix generated URLs
        run: |
          find . -name "*.md" ! -path "./_site/*" -exec sed -i 's|/pages/adafede/sparql-examples/|/sparql-examples/|g' {} +

      - name: Write Jekyll config
        run: |
          cat > _config.yml << 'EOF'
          baseurl: "/sparql-examples"
          url: "https://adafede.codeberg.page"
          theme: null
          EOF

      - name: Build with Jekyll
        uses: https://github.com/actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Deploy to Codeberg Pages
        uses: actions/git-pages@v2
        with:
          site: https://adafede.codeberg.page/sparql-examples/
          token: ${{ forge.token }}
          source: ./_site